#!/bin/bash

# Switch to root user
sudo -i

# Step 1: Download and install Cloudflare GPG key
curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ jammy main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list

# Step 3: Update package list and install Cloudflare WARP
sudo apt-get update && apt-get install cloudflare-warp


cat << EOF > /var/lib/cloudflare-warp/mdm.xml
<dict>
  <key>organization</key>
  <string>cloudpioneers</string>
  <key>30ee99da046b41a6b96e82fbdd69d7cb.access</key>
  <string>your_client_id_access_value</string>
  <key>cbbb8a760f4b103a5766864153de08f481199bf5a4194b7a2f4a8f91a2c2771d</key>
  <string>your_client_secret_value</string>
  <key>warp_connector_token</key>
  <string>eyJhIjoiZjBiMGZiNTIxZTk0ZTkxYTQzY2VmMmNlNjYxYTlhYWEiLCJ0IjoiNmJhZjk3YzYtYWMyOS00NjEwLWEzYjItMjY0MDQyNzAyZGE4IiwicyI6IlpUYzBObUU0TXpBdE5EQXpOUzAwWldRekxUbGhaRGN0TkRBMlpXTmhZV1UxTkRVeCJ9</string>
</dict>
EOF


cat << EOF > /var/lib/cloudflare-warp/mdm.xml
<dict>
  <key>organization</key>
  <string>cloudpioneers</string>
  <key>auth_client_id</key>
  <string>30ee99da046b41a6b96e82fbdd69d7cb.access</string>
  <key>auth_client_secret</key>
  <string>cbbb8a760f4b103a5766864153de08f481199bf5a4194b7a2f4a8f91a2c2771d</string>
  <key>warp_connector_token</key>
  <string>eyJhIjoiZjBiMGZiNTIxZTk0ZTkxYTQzY2VmMmNlNjYxYTlhYWEiLCJ0IjoiNmJhZjk3YzYtYWMyOS00NjEwLWEzYjItMjY0MDQyNzAyZGE4IiwicyI6IlpUYzBObUU0TXpBdE5EQXpOUzAwWldRekxUbGhaRGN0TkRBMlpXTmhZV1UxTkRVeCJ9</string>
</dict>
EOF

## WARP CONNECTOR ##
# INSTALL ON ROUTER OR EDGE DEVICE 
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/warp-connector/
# Step 4: Set variables for MDM configuration
ORGANIZATION="cloudpioneers"
AUTH_CLIENT_ID="your_client_id_access_value"
AUTH_CLIENT_SECRET="your_client_secret_value"
WARP_CONNECTOR_TOKEN="eyJhIjoiZjBiMGZiNTIxZTk0ZTkxYTQzY2VmMmNlNjYxYTlhYWEiLCJ0IjoiNmJhZjk3YzYtYWMyOS00NjEwLWEzYjItMjY0MDQyNzAyZGE4IiwicyI6IlpUYzBObUU0TXpBdE5EQXpOUzAwWldRekxUbGhaRGN0TkRBMlpXTmhZV1UxTkRVeCJ9"

# Step 5: Create MDM configuration file
cat << EOF > /var/lib/cloudflare-warp/mdm.xml
<dict>
  <key>organization</key>
  <string>$ORGANIZATION</string>
  <key>auth_client_id</key>
  <string>$AUTH_CLIENT_ID</string>
  <key>auth_client_secret</key>
  <string>$AUTH_CLIENT_SECRET</string>
  <key>warp_connector_token</key>
  <string>$WARP_CONNECTOR_TOKEN</string>
</dict>
EOF

# Step 6: Exclude private routes before enrolling and connecting
warp-cli add-excluded-route 10.0.0.0/8
warp-cli add-excluded-route 172.16.0.0/12
warp-cli add-excluded-route 192.168.0.0/16

# Configure host
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t mangle -A FORWARD -i CloudflareWARP -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
sudo iptables -t mangle -A FORWARD -o CloudflareWARP -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu

# REGISTER and CONNECT
warp-cli register
warp-cli connect


# Step 8: Restart WARP service
systemctl restart warp-svc.service
systemctl enable warp-svc.service

# Step 9: Check WARP account status
warp-cli account

# Step 10: Check WARP connection status
warp-cli status
