---
- name: Comprehensive System Maintenance Playbook
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Update and upgrade system
      apt:
        update_cache: yes
        upgrade: full
        dist_upgrade: yes
        autoremove: yes
        autoclean: yes
        fix_broken: yes
        install_recommends: yes
      register: apt_result

    - name: Clean apt cache and configure packages
      shell: |
        apt-get clean
        dpkg --configure -a
      changed_when: false

    - name: Update grub
      command: update-grub
      changed_when: false

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

  handlers:
    - name: Reboot system
      reboot:
      when: reboot_required.stat.exists or apt_result.changed
