---
- name: System Maintenance Playbook for Alpine Linux
  hosts: all  # Change this to your specific host group if needed
  become: true  # Use become to run tasks with sudo privileges
  tasks:
    - name: Update apk package index
      apk:
        update_cache: yes

    - name: Upgrade installed packages
      apk:
        upgrade: yes

    - name: Fix broken dependencies
      command: apk fix

    - name: Remove unnecessary packages
      apk:
        state: absent
        name: "{{ item }}"
      loop:
        - some-package  # Replace with actual packages you want to remove
        - another-package  # Add more packages as needed

    - name: Clean up apk cache
      command: apk cache clean

    - name: Install any missing dependencies
      apk:
        name: "{{ item }}"
        state: present
      loop:
        - package1  # Replace with actual package names
        - package2  # Add more packages as needed
